version: '3'
services:
  frontend:
    build: ./public
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb+srv://christianfleischhauer007:rPzDVDi7YUgsN7vj@cluster0.wimqjvk.mongodb.net/
    
  
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend