version: '3'
services:
  frontend:
    build: ./public
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb+srv://christianfleischhauer007:rPzDVDi7YUgsN7vj@cluster0.wimqjvk.mongodb.net/
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
