# Set the base image to use for Node.js
FROM node:18-alpine as build

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package.json package-lock.json ./

# Install the dependencies
RUN npm i

# Copy the rest of the application source code to the container
COPY . .

# Build the frontend application
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]